# Kitty colors from Noctalia dynamic theme
# Generated at Wed Jun 24 00:48:56 +05 2026

# Background & Foreground
background #282828
foreground #fbf1c7

# Selection
selection_background #3c3836
selection_foreground #ebdbb2

# Black
color0  #3c3836
color8  #57514e

# Red
color1  #fb4934
color9  #fb4934

# Green
color2  #83a598
color10 #83a598

# Yellow
color3  #83a598
color11 #83a598

# Blue
color4  #fabd2f
color12 #fabd2f

# Magenta
color5  #b8bb26
color13 #b8bb26

# Cyan
color6  #282828
color14 #282828

# White
color7  #ebdbb2
color15 #fbf1c7

# Cursor
cursor            #b8bb26
cursor_text_color #282828
